services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: db
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    volumes:
      - ./backend:/app  # Монтируем ./backend на /app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'
    environment:
      NUXT_PUBLIC_BACKEND_API: http://localhost:3001/api

volumes:
  pgdata:
